BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW paper_quality_metrics';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW user_engagement_report';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW trending_topics';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW most_active_authors';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW most_cited_papers';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  FOR item IN (SELECT table_name FROM user_tables WHERE table_name NOT LIKE 'DR$%') LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || item.table_name || ' CASCADE CONSTRAINTS PURGE';
  END LOOP;
END;
/
CREATE TABLE USERS (
    user_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL UNIQUE,
    email VARCHAR2(100) NOT NULL UNIQUE,
    password_hash VARCHAR2(255) NOT NULL,
    full_name VARCHAR2(100) NOT NULL,
    role VARCHAR2(20) DEFAULT 'researcher' NOT NULL CHECK (role IN ('researcher', 'student', 'admin', 'librarian')),
    affiliation VARCHAR2(150),
    country VARCHAR2(50),
    profile_picture_url VARCHAR2(255),
    bio CLOB,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    is_active NUMBER(1) DEFAULT 1 NOT NULL CHECK (is_active IN (0, 1)),
    is_verified NUMBER(1) DEFAULT 0 NOT NULL CHECK (is_verified IN (0, 1)),
    last_login TIMESTAMP
);
CREATE INDEX idx_users_email ON USERS(email);
CREATE INDEX idx_users_username ON USERS(username);
CREATE INDEX idx_users_created_at ON USERS(created_at);
CREATE INDEX idx_users_is_active ON USERS(is_active);
CREATE TABLE AUTHORS (
    author_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(100) NOT NULL,
    affiliation VARCHAR2(150),
    country VARCHAR2(50),
    email VARCHAR2(100),
    h_index NUMBER CHECK (h_index >= 0),
    biography CLOB,
    researcher_url VARCHAR2(255),
    orcid VARCHAR2(50) UNIQUE,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX idx_authors_full_name ON AUTHORS(full_name);
CREATE INDEX idx_authors_affiliation ON AUTHORS(affiliation);
CREATE INDEX idx_authors_orcid ON AUTHORS(orcid);
CREATE INDEX idx_authors_h_index ON AUTHORS(h_index);
CREATE TABLE JOURNALS (
    journal_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(200) NOT NULL UNIQUE,
    issn VARCHAR2(20) UNIQUE,
    publisher VARCHAR2(150),
    impact_factor NUMBER(5,3) CHECK (impact_factor >= 0),
    h_index NUMBER CHECK (h_index >= 0),
    quartile VARCHAR2(2) DEFAULT 'NA' NOT NULL CHECK (quartile IN ('Q1', 'Q2', 'Q3', 'Q4', 'NA')),
    website VARCHAR2(255),
    description CLOB,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX idx_journals_name ON JOURNALS(name);
CREATE INDEX idx_journals_issn ON JOURNALS(issn);
CREATE INDEX idx_journals_impact_factor ON JOURNALS(impact_factor);
CREATE INDEX idx_journals_quartile ON JOURNALS(quartile);
CREATE TABLE RESEARCH_FIELDS (
    field_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    field_name VARCHAR2(100) NOT NULL UNIQUE,
    description CLOB,
    parent_field_id NUMBER,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_parent_field FOREIGN KEY (parent_field_id) REFERENCES RESEARCH_FIELDS(field_id) ON DELETE SET NULL
);
CREATE INDEX idx_research_fields_name ON RESEARCH_FIELDS(field_name);
CREATE INDEX idx_research_fields_parent ON RESEARCH_FIELDS(parent_field_id);
CREATE TABLE RESEARCH_PAPERS (
    paper_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    title VARCHAR2(300) NOT NULL,
    abstract CLOB NOT NULL,
    publication_date DATE NOT NULL,
    doi VARCHAR2(100) UNIQUE,
    journal_id NUMBER,
    volume NUMBER CHECK (volume > 0),
    issue NUMBER CHECK (issue > 0),
    pages VARCHAR2(20),
    citation_count NUMBER DEFAULT 0 NOT NULL CHECK (citation_count >= 0),
    view_count NUMBER DEFAULT 0 NOT NULL CHECK (view_count >= 0),
    download_count NUMBER DEFAULT 0 NOT NULL CHECK (download_count >= 0),
    pdf_url VARCHAR2(255),
    language VARCHAR2(20) DEFAULT 'English' NOT NULL,
    is_peer_reviewed NUMBER(1) DEFAULT 1 NOT NULL CHECK (is_peer_reviewed IN (0, 1)),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_journal FOREIGN KEY (journal_id) REFERENCES JOURNALS(journal_id) ON DELETE SET NULL
);
CREATE INDEX idx_research_papers_doi ON RESEARCH_PAPERS(doi);
CREATE INDEX idx_research_papers_title ON RESEARCH_PAPERS(title);
CREATE INDEX idx_research_papers_date ON RESEARCH_PAPERS(publication_date);
CREATE INDEX idx_research_papers_journal ON RESEARCH_PAPERS(journal_id);
CREATE INDEX idx_research_papers_citations ON RESEARCH_PAPERS(citation_count);
CREATE INDEX idx_research_papers_views ON RESEARCH_PAPERS(view_count);
CREATE INDEX idx_research_papers_title_text ON RESEARCH_PAPERS(title) INDEXTYPE IS CTXSYS.CONTEXT;
CREATE INDEX idx_research_papers_abstract_text ON RESEARCH_PAPERS(abstract) INDEXTYPE IS CTXSYS.CONTEXT;
CREATE TABLE KEYWORDS (
    keyword_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    keyword VARCHAR2(100) NOT NULL UNIQUE,
    frequency NUMBER DEFAULT 0 NOT NULL CHECK (frequency >= 0),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX idx_keywords_keyword ON KEYWORDS(keyword);
CREATE INDEX idx_keywords_frequency ON KEYWORDS(frequency);
CREATE TABLE REVIEWS (
    review_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    paper_id NUMBER NOT NULL,
    rating NUMBER NOT NULL CHECK (rating BETWEEN 1 AND 5),
    review_text CLOB,
    is_helpful NUMBER DEFAULT 0 NOT NULL CHECK (is_helpful >= 0),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_review_user FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_review_paper FOREIGN KEY (paper_id) REFERENCES RESEARCH_PAPERS(paper_id) ON DELETE CASCADE,
    CONSTRAINT unique_user_paper_review UNIQUE (user_id, paper_id)
);
CREATE INDEX idx_reviews_user ON REVIEWS(user_id);
CREATE INDEX idx_reviews_paper ON REVIEWS(paper_id);
CREATE INDEX idx_reviews_rating ON REVIEWS(rating);
CREATE INDEX idx_reviews_created_at ON REVIEWS(created_at);
CREATE TABLE PAPER_AUTHORS (
    paper_id NUMBER NOT NULL,
    author_id NUMBER NOT NULL,
    author_order NUMBER NOT NULL CHECK (author_order > 0),
    PRIMARY KEY (paper_id, author_id),
    CONSTRAINT fk_paper_authors_paper FOREIGN KEY (paper_id) REFERENCES RESEARCH_PAPERS(paper_id) ON DELETE CASCADE,
    CONSTRAINT fk_paper_authors_author FOREIGN KEY (author_id) REFERENCES AUTHORS(author_id) ON DELETE CASCADE
);
CREATE INDEX idx_paper_authors_author ON PAPER_AUTHORS(author_id);
CREATE INDEX idx_paper_authors_order ON PAPER_AUTHORS(paper_id, author_order);
CREATE TABLE PAPER_FIELDS (
    paper_id NUMBER NOT NULL,
    field_id NUMBER NOT NULL,
    relevance_score NUMBER(3,2) CHECK (relevance_score BETWEEN 0 AND 1),
    PRIMARY KEY (paper_id, field_id),
    CONSTRAINT fk_paper_fields_paper FOREIGN KEY (paper_id) REFERENCES RESEARCH_PAPERS(paper_id) ON DELETE CASCADE,
    CONSTRAINT fk_paper_fields_field FOREIGN KEY (field_id) REFERENCES RESEARCH_FIELDS(field_id) ON DELETE CASCADE
);
CREATE INDEX idx_paper_fields_field ON PAPER_FIELDS(field_id);
CREATE INDEX idx_paper_fields_score ON PAPER_FIELDS(paper_id, relevance_score);
CREATE TABLE PAPER_KEYWORDS (
    paper_id NUMBER NOT NULL,
    keyword_id NUMBER NOT NULL,
    PRIMARY KEY (paper_id, keyword_id),
    CONSTRAINT fk_paper_keywords_paper FOREIGN KEY (paper_id) REFERENCES RESEARCH_PAPERS(paper_id) ON DELETE CASCADE,
    CONSTRAINT fk_paper_keywords_keyword FOREIGN KEY (keyword_id) REFERENCES KEYWORDS(keyword_id) ON DELETE CASCADE
);
CREATE INDEX idx_paper_keywords_keyword ON PAPER_KEYWORDS(keyword_id);
CREATE TABLE SAVED_PAPERS (
    saved_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    paper_id NUMBER NOT NULL,
    collection_name VARCHAR2(100),
    saved_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_saved_papers_user FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_saved_papers_paper FOREIGN KEY (paper_id) REFERENCES RESEARCH_PAPERS(paper_id) ON DELETE CASCADE,
    CONSTRAINT unique_user_saved_paper UNIQUE (user_id, paper_id)
);
CREATE INDEX idx_saved_papers_user ON SAVED_PAPERS(user_id);
CREATE INDEX idx_saved_papers_paper ON SAVED_PAPERS(paper_id);
CREATE INDEX idx_saved_papers_saved_at ON SAVED_PAPERS(user_id, saved_at);
CREATE TABLE COLLECTIONS (
    collection_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    name VARCHAR2(100) NOT NULL,
    description VARCHAR2(500),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_collections_user FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE,
    CONSTRAINT unique_user_collection UNIQUE (user_id, name)
);
CREATE INDEX idx_collections_user ON COLLECTIONS(user_id);
CREATE INDEX idx_collections_updated_at ON COLLECTIONS(user_id, updated_at);
CREATE TABLE FOLLOWED_AUTHORS (
    follow_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    author_id NUMBER NOT NULL,
    followed_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_followed_authors_user FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_followed_authors_author FOREIGN KEY (author_id) REFERENCES AUTHORS(author_id) ON DELETE CASCADE,
    CONSTRAINT unique_user_followed_author UNIQUE (user_id, author_id)
);
CREATE INDEX idx_followed_authors_user ON FOLLOWED_AUTHORS(user_id);
CREATE INDEX idx_followed_authors_author ON FOLLOWED_AUTHORS(author_id);
CREATE INDEX idx_followed_authors_at ON FOLLOWED_AUTHORS(user_id, followed_at);
CREATE TABLE CITATIONS (
    citation_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    citing_paper_id NUMBER NOT NULL,
    cited_paper_id NUMBER NOT NULL,
    context CLOB,
    CONSTRAINT fk_citations_citing FOREIGN KEY (citing_paper_id) REFERENCES RESEARCH_PAPERS(paper_id) ON DELETE CASCADE,
    CONSTRAINT fk_citations_cited FOREIGN KEY (cited_paper_id) REFERENCES RESEARCH_PAPERS(paper_id) ON DELETE CASCADE,
    CONSTRAINT unique_citation_pair UNIQUE (citing_paper_id, cited_paper_id)
);
CREATE INDEX idx_citations_cited ON CITATIONS(cited_paper_id);
CREATE INDEX idx_citations_citing ON CITATIONS(citing_paper_id);
CREATE TABLE SEARCH_HISTORY (
    search_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER,
    search_query VARCHAR2(500) NOT NULL,
    filters_applied CLOB CHECK (filters_applied IS JSON),
    results_count NUMBER DEFAULT 0 NOT NULL CHECK (results_count >= 0),
    search_type VARCHAR2(20) NOT NULL CHECK (search_type IN ('simple', 'keyword', 'author', 'field', 'advanced')),
    searched_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_search_history_user FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE SET NULL
);
CREATE INDEX idx_search_history_user ON SEARCH_HISTORY(user_id);
CREATE INDEX idx_search_history_at ON SEARCH_HISTORY(searched_at);
CREATE INDEX idx_search_history_type ON SEARCH_HISTORY(search_type);
CREATE INDEX idx_search_history_user_at ON SEARCH_HISTORY(user_id, searched_at);
CREATE TABLE AUDIT_LOGS (
    log_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER,
    table_name VARCHAR2(50) NOT NULL,
    action VARCHAR2(10) NOT NULL CHECK (action IN ('INSERT', 'UPDATE', 'DELETE')),
    record_id NUMBER NOT NULL,
    old_values CLOB CHECK (old_values IS JSON),
    new_values CLOB CHECK (new_values IS JSON),
    action_timestamp TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_audit_logs_user FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE SET NULL
);
CREATE INDEX idx_audit_logs_user ON AUDIT_LOGS(user_id);
CREATE INDEX idx_audit_logs_table ON AUDIT_LOGS(table_name);
CREATE INDEX idx_audit_logs_timestamp ON AUDIT_LOGS(action_timestamp);
CREATE INDEX idx_audit_logs_action ON AUDIT_LOGS(action);
CREATE INDEX idx_audit_logs_user_time ON AUDIT_LOGS(user_id, action_timestamp);
CREATE TABLE USER_ACTIVITY (
    activity_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    activity_type VARCHAR2(20) NOT NULL CHECK (activity_type IN ('view', 'download', 'save', 'review', 'search')),
    paper_id NUMBER,
    activity_timestamp TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_user_activity_user FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_user_activity_paper FOREIGN KEY (paper_id) REFERENCES RESEARCH_PAPERS(paper_id) ON DELETE SET NULL
);
CREATE INDEX idx_user_activity_user ON USER_ACTIVITY(user_id);
CREATE INDEX idx_user_activity_paper ON USER_ACTIVITY(paper_id);
CREATE INDEX idx_user_activity_type ON USER_ACTIVITY(activity_type);
CREATE INDEX idx_user_activity_timestamp ON USER_ACTIVITY(activity_timestamp);
CREATE INDEX idx_user_activity_user_time ON USER_ACTIVITY(user_id, activity_timestamp);
CREATE TABLE NOTIFICATIONS (
    notification_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    title VARCHAR2(200) NOT NULL,
    body VARCHAR2(1000) NOT NULL,
    type VARCHAR2(30) DEFAULT 'system' NOT NULL,
    is_read NUMBER(1) DEFAULT 0 NOT NULL CHECK (is_read IN (0, 1)),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    read_at TIMESTAMP,
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE
);
CREATE INDEX idx_notifications_user ON NOTIFICATIONS(user_id);
CREATE INDEX idx_notifications_read ON NOTIFICATIONS(user_id, is_read);
CREATE INDEX idx_notifications_created_at ON NOTIFICATIONS(user_id, created_at);
CREATE TABLE RESEARCH_REQUESTS (
    request_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    title VARCHAR2(200) NOT NULL,
    recipient_name VARCHAR2(150) NOT NULL,
    message CLOB NOT NULL,
    status VARCHAR2(20) DEFAULT 'pending' NOT NULL CHECK (status IN ('pending', 'approved', 'declined', 'archived')),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_research_requests_user FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE
);
CREATE INDEX idx_research_requests_user ON RESEARCH_REQUESTS(user_id);
CREATE INDEX idx_research_requests_status ON RESEARCH_REQUESTS(user_id, status);
CREATE TABLE USER_SETTINGS (
    user_id NUMBER PRIMARY KEY,
    theme VARCHAR2(20) DEFAULT 'system' NOT NULL CHECK (theme IN ('light', 'dark', 'system')),
    density VARCHAR2(20) DEFAULT 'comfortable' NOT NULL CHECK (density IN ('comfortable', 'compact')),
    notifications CLOB CHECK (notifications IS JSON),
    privacy CLOB CHECK (privacy IS JSON),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_user_settings_user FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE
);
CREATE TABLE QUESTIONS (
    question_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    title VARCHAR2(500) NOT NULL,
    body CLOB,
    category VARCHAR2(100),
    view_count NUMBER DEFAULT 0 NOT NULL CHECK (view_count >= 0),
    answer_count NUMBER DEFAULT 0 NOT NULL CHECK (answer_count >= 0),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_questions_user FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE
);
CREATE INDEX idx_questions_user ON QUESTIONS(user_id);
CREATE INDEX idx_questions_created_at ON QUESTIONS(created_at);
CREATE INDEX idx_questions_category ON QUESTIONS(category);
CREATE TABLE ANSWERS (
    answer_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    question_id NUMBER NOT NULL,
    user_id NUMBER NOT NULL,
    body CLOB NOT NULL,
    upvotes NUMBER DEFAULT 0 NOT NULL CHECK (upvotes >= 0),
    is_accepted NUMBER(1) DEFAULT 0 NOT NULL CHECK (is_accepted IN (0, 1)),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_answers_question FOREIGN KEY (question_id) REFERENCES QUESTIONS(question_id) ON DELETE CASCADE,
    CONSTRAINT fk_answers_user FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE
);
CREATE INDEX idx_answers_question ON ANSWERS(question_id);
CREATE INDEX idx_answers_user ON ANSWERS(user_id);
CREATE TABLE EMAIL_QUEUE (
    email_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    requester_user_id NUMBER,
    recipient_email VARCHAR2(255) NOT NULL,
    subject VARCHAR2(500) NOT NULL,
    body CLOB NOT NULL,
    status VARCHAR2(20) DEFAULT 'pending' NOT NULL CHECK (status IN ('pending', 'sending', 'sent', 'failed')),
    error_message CLOB,
    queued_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    sent_at TIMESTAMP,
    CONSTRAINT fk_email_queue_user FOREIGN KEY (requester_user_id) REFERENCES USERS(user_id) ON DELETE SET NULL
);
CREATE INDEX idx_email_queue_user ON EMAIL_QUEUE(requester_user_id);
CREATE INDEX idx_email_queue_status ON EMAIL_QUEUE(status);
CREATE TABLE RESEARCHER_STATS (
    user_id NUMBER PRIMARY KEY,
    saved_papers NUMBER DEFAULT 0 NOT NULL,
    following NUMBER DEFAULT 0 NOT NULL,
    followers NUMBER DEFAULT 0 NOT NULL,
    reviews NUMBER DEFAULT 0 NOT NULL,
    questions NUMBER DEFAULT 0 NOT NULL,
    answers NUMBER DEFAULT 0 NOT NULL,
    full_text_requests NUMBER DEFAULT 0 NOT NULL,
    total_reads NUMBER DEFAULT 0 NOT NULL,
    rg_score NUMBER DEFAULT 0 NOT NULL,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_researcher_stats_user FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE
);
CREATE INDEX idx_researcher_stats_rg_score ON RESEARCHER_STATS(rg_score);
CREATE TABLE JOBS (
    job_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    employer VARCHAR2(200) NOT NULL,
    title VARCHAR2(200) NOT NULL,
    location VARCHAR2(200) NOT NULL,
    description CLOB,
    requirements CLOB,
    salary_range VARCHAR2(100),
    employment_type VARCHAR2(50) DEFAULT 'Full-time' NOT NULL CHECK (employment_type IN ('Full-time', 'Part-time', 'Contract', 'Temporary', 'Internship')),
    posted_by NUMBER,
    posted_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    expires_at TIMESTAMP,
    CONSTRAINT fk_jobs_posted_by FOREIGN KEY (posted_by) REFERENCES USERS(user_id) ON DELETE SET NULL
);
CREATE INDEX idx_jobs_employer ON JOBS(employer);
CREATE INDEX idx_jobs_location ON JOBS(location);
CREATE INDEX idx_jobs_posted_at ON JOBS(posted_at);
CREATE INDEX idx_jobs_title_text ON JOBS(title) INDEXTYPE IS CTXSYS.CONTEXT;
CREATE TABLE SAVED_JOBS (
    saved_job_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    job_id NUMBER NOT NULL,
    saved_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_saved_jobs_user FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_saved_jobs_job FOREIGN KEY (job_id) REFERENCES JOBS(job_id) ON DELETE CASCADE,
    CONSTRAINT unique_user_saved_job UNIQUE (user_id, job_id)
);
CREATE INDEX idx_saved_jobs_user ON SAVED_JOBS(user_id);
CREATE INDEX idx_saved_jobs_job ON SAVED_JOBS(job_id);
CREATE TABLE PAPER_RECOMMENDATIONS (
    recommendation_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    paper_id NUMBER NOT NULL,
    recommended_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_paper_rec_user FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_paper_rec_paper FOREIGN KEY (paper_id) REFERENCES RESEARCH_PAPERS(paper_id) ON DELETE CASCADE,
    CONSTRAINT unique_user_paper_rec UNIQUE (user_id, paper_id)
);
CREATE INDEX idx_paper_rec_user ON PAPER_RECOMMENDATIONS(user_id);
CREATE INDEX idx_paper_rec_paper ON PAPER_RECOMMENDATIONS(paper_id);
CREATE TABLE QUESTIONS_FOLLOWERS (
    follow_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    question_id NUMBER NOT NULL,
    followed_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_qf_user FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_qf_question FOREIGN KEY (question_id) REFERENCES QUESTIONS(question_id) ON DELETE CASCADE,
    CONSTRAINT unique_user_question_follow UNIQUE (user_id, question_id)
);
CREATE INDEX idx_qf_user ON QUESTIONS_FOLLOWERS(user_id);
CREATE INDEX idx_qf_question ON QUESTIONS_FOLLOWERS(question_id);
CREATE TABLE USER_EDUCATION (
    education_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    institution VARCHAR2(200) NOT NULL,
    degree VARCHAR2(100),
    field_of_study VARCHAR2(150),
    start_year NUMBER(4),
    end_year NUMBER(4),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_user_edu_user FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE
);
CREATE INDEX idx_user_edu_user ON USER_EDUCATION(user_id);

CREATE TABLE USER_EXPERIENCE (
    experience_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    company VARCHAR2(200) NOT NULL,
    position VARCHAR2(150),
    start_date DATE,
    end_date DATE,
    description CLOB,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_user_exp_user FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE
);
CREATE INDEX idx_user_exp_user ON USER_EXPERIENCE(user_id);

CREATE TABLE USER_SKILLS (
    skill_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    skill_name VARCHAR2(100) NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_user_skill_user FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE,
    CONSTRAINT unique_user_skill UNIQUE (user_id, skill_name)
);
CREATE INDEX idx_user_skill_user ON USER_SKILLS(user_id);

CREATE TABLE USER_LANGUAGES (
    language_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    language_name VARCHAR2(100) NOT NULL,
    proficiency VARCHAR2(50),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_user_lang_user FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE,
    CONSTRAINT unique_user_language UNIQUE (user_id, language_name)
);
CREATE INDEX idx_user_lang_user ON USER_LANGUAGES(user_id);

CREATE TABLE USER_DISCIPLINES (
    discipline_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    discipline_name VARCHAR2(100) NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_user_disc_user FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE,
    CONSTRAINT unique_user_discipline UNIQUE (user_id, discipline_name)
);
CREATE INDEX idx_user_disc_user ON USER_DISCIPLINES(user_id);

CREATE OR REPLACE VIEW most_cited_papers AS
SELECT 
    rp.paper_id,
    rp.title,
    rp.publication_date,
    rp.citation_count,
    j.name AS journal_name,
    LISTAGG(a.full_name, ', ') WITHIN GROUP (ORDER BY pa.author_order) AS authors
FROM RESEARCH_PAPERS rp
LEFT JOIN JOURNALS j ON rp.journal_id = j.journal_id
LEFT JOIN PAPER_AUTHORS pa ON rp.paper_id = pa.paper_id
LEFT JOIN AUTHORS a ON pa.author_id = a.author_id
GROUP BY rp.paper_id, rp.title, rp.publication_date, rp.citation_count, j.name;
CREATE OR REPLACE VIEW most_active_authors AS
SELECT 
    a.author_id,
    a.full_name,
    a.affiliation,
    COUNT(pa.paper_id) AS paper_count,
    a.h_index,
    MAX(rp.publication_date) AS latest_publication
FROM AUTHORS a
LEFT JOIN PAPER_AUTHORS pa ON a.author_id = pa.author_id
LEFT JOIN RESEARCH_PAPERS rp ON pa.paper_id = rp.paper_id
GROUP BY a.author_id, a.full_name, a.affiliation, a.h_index;
CREATE OR REPLACE VIEW trending_topics AS
SELECT 
    k.keyword_id,
    k.keyword,
    COUNT(pk.paper_id) AS paper_count,
    k.frequency,
    MAX(rp.publication_date) AS latest_mention
FROM KEYWORDS k
LEFT JOIN PAPER_KEYWORDS pk ON k.keyword_id = pk.keyword_id
LEFT JOIN RESEARCH_PAPERS rp ON pk.paper_id = rp.paper_id
WHERE EXTRACT(YEAR FROM rp.publication_date) >= EXTRACT(YEAR FROM SYSDATE) - 2
GROUP BY k.keyword_id, k.keyword, k.frequency;
CREATE OR REPLACE VIEW user_engagement_report AS
SELECT 
    u.user_id,
    u.full_name,
    u.email,
    COUNT(DISTINCT ua.activity_id) AS total_activities,
    COUNT(DISTINCT sp.saved_id) AS saved_papers,
    COUNT(DISTINCT r.review_id) AS reviews_written,
    COUNT(DISTINCT fa.follow_id) AS authors_followed,
    u.last_login
FROM USERS u
LEFT JOIN USER_ACTIVITY ua ON u.user_id = ua.user_id
LEFT JOIN SAVED_PAPERS sp ON u.user_id = sp.user_id
LEFT JOIN REVIEWS r ON u.user_id = r.user_id
LEFT JOIN FOLLOWED_AUTHORS fa ON u.user_id = fa.user_id
GROUP BY u.user_id, u.full_name, u.email, u.last_login;
CREATE OR REPLACE VIEW paper_quality_metrics AS
SELECT 
    rp.paper_id,
    rp.title,
    rp.publication_date,
    j.impact_factor,
    j.quartile,
    rp.citation_count,
    rp.view_count,
    rp.download_count,
    AVG(rv.rating) AS avg_review_rating,
    COUNT(rv.review_id) AS review_count,
    (rp.citation_count + rp.view_count * 0.1 + rp.download_count * 0.05) AS engagement_score
FROM RESEARCH_PAPERS rp
LEFT JOIN JOURNALS j ON rp.journal_id = j.journal_id
LEFT JOIN REVIEWS rv ON rp.paper_id = rv.paper_id
GROUP BY rp.paper_id, rp.title, rp.publication_date, j.impact_factor, j.quartile, rp.citation_count, rp.view_count, rp.download_count;
