const fs = require('fs');
const path = require('path');

const schemaPath = path.join(__dirname, '..', '..', '..', '..', '02_CREATE_TABLES.sql');

describe('database schema consistency', () => {
  const schema = fs.readFileSync(schemaPath, 'utf8');
  const legacyCreateDatabase = ['CREATE', 'DATABASE', 'IF', 'NOT', 'EXISTS'].join(' ');
  const legacyUseStatement = ['USE', 'researchhub'].join(' ');

  it('uses Oracle DDL for the schema used by the API and seed scripts', () => {
    expect(schema).toContain('GENERATED BY DEFAULT ON NULL AS IDENTITY');
    expect(schema).toContain('VARCHAR2');
    expect(schema).toContain('SYSTIMESTAMP');
    expect(schema).not.toContain(legacyCreateDatabase);
    expect(schema).not.toContain(legacyUseStatement);
  });

  it('uses the table names expected by API models and seed data', () => {
    for (const table of ['USERS', 'AUTHORS', 'JOURNALS', 'RESEARCH_FIELDS', 'RESEARCH_PAPERS', 'KEYWORDS']) {
      expect(schema).toContain(`CREATE TABLE ${table}`);
    }
  });

  it('contains tables for user-ready dynamic website modules', () => {
    for (const table of ['COLLECTIONS', 'NOTIFICATIONS', 'RESEARCH_REQUESTS', 'USER_SETTINGS']) {
      expect(schema).toContain(`CREATE TABLE ${table}`);
    }
  });

  it('allows seed search history values', () => {
    expect(schema).toContain("search_type VARCHAR2(20) NOT NULL CHECK (search_type IN ('simple', 'keyword', 'author', 'field', 'advanced'))");
  });

  it('uses Oracle Text indexes for paper search', () => {
    expect(schema).toContain('INDEXTYPE IS CTXSYS.CONTEXT');
  });
});
