-- Phase 1/2 foundation: public researcher profiles, normalized RBAC, and moderation.
-- Every block is idempotent so it can be applied to an existing Oracle schema.

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE RESEARCHER_PROFILES (
      user_id NUMBER PRIMARY KEY,
      slug VARCHAR2(100) NOT NULL UNIQUE,
      headline VARCHAR2(255),
      department VARCHAR2(150),
      position_title VARCHAR2(150),
      website_url VARCHAR2(500),
      orcid VARCHAR2(50),
      visibility VARCHAR2(20) DEFAULT 'public' NOT NULL
        CHECK (visibility IN ('public', 'network', 'private')),
      profile_completed_at TIMESTAMP,
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT fk_researcher_profiles_user FOREIGN KEY (user_id)
        REFERENCES USERS(user_id) ON DELETE CASCADE,
      CONSTRAINT uq_researcher_profiles_orcid UNIQUE (orcid)
    )
  ]';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE USER_FOLLOWS (
      follower_user_id NUMBER NOT NULL,
      followed_user_id NUMBER NOT NULL,
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT pk_user_follows PRIMARY KEY (follower_user_id, followed_user_id),
      CONSTRAINT ck_user_follows_distinct CHECK (follower_user_id <> followed_user_id),
      CONSTRAINT fk_user_follows_follower FOREIGN KEY (follower_user_id)
        REFERENCES USERS(user_id) ON DELETE CASCADE,
      CONSTRAINT fk_user_follows_followed FOREIGN KEY (followed_user_id)
        REFERENCES USERS(user_id) ON DELETE CASCADE
    )
  ]';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE USER_AUTHOR_CLAIMS (
      claim_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
      user_id NUMBER NOT NULL,
      author_id NUMBER NOT NULL,
      status VARCHAR2(20) DEFAULT 'pending' NOT NULL
        CHECK (status IN ('pending', 'verified', 'rejected')),
      reviewed_by_user_id NUMBER,
      reviewed_at TIMESTAMP,
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT uq_user_author_claim UNIQUE (user_id, author_id),
      CONSTRAINT fk_user_author_claim_user FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE,
      CONSTRAINT fk_user_author_claim_author FOREIGN KEY (author_id) REFERENCES AUTHORS(author_id) ON DELETE CASCADE,
      CONSTRAINT fk_user_author_claim_reviewer FOREIGN KEY (reviewed_by_user_id) REFERENCES USERS(user_id) ON DELETE SET NULL
    )
  ]';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE ROLE_DEFINITIONS (
      role_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
      role_key VARCHAR2(50) NOT NULL UNIQUE,
      display_name VARCHAR2(100) NOT NULL,
      description VARCHAR2(500),
      is_system NUMBER(1) DEFAULT 0 NOT NULL CHECK (is_system IN (0, 1)),
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )
  ]';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE PERMISSION_DEFINITIONS (
      permission_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
      permission_key VARCHAR2(100) NOT NULL UNIQUE,
      description VARCHAR2(500),
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )
  ]';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE ROLE_PERMISSIONS (
      role_id NUMBER NOT NULL,
      permission_id NUMBER NOT NULL,
      CONSTRAINT pk_role_permissions PRIMARY KEY (role_id, permission_id),
      CONSTRAINT fk_role_permissions_role FOREIGN KEY (role_id)
        REFERENCES ROLE_DEFINITIONS(role_id) ON DELETE CASCADE,
      CONSTRAINT fk_role_permissions_permission FOREIGN KEY (permission_id)
        REFERENCES PERMISSION_DEFINITIONS(permission_id) ON DELETE CASCADE
    )
  ]';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE USER_ROLE_ASSIGNMENTS (
      user_id NUMBER NOT NULL,
      role_id NUMBER NOT NULL,
      assigned_by_user_id NUMBER,
      assigned_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      expires_at TIMESTAMP,
      CONSTRAINT pk_user_role_assignments PRIMARY KEY (user_id, role_id),
      CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE,
      CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES ROLE_DEFINITIONS(role_id) ON DELETE CASCADE,
      CONSTRAINT fk_user_roles_assigned_by FOREIGN KEY (assigned_by_user_id) REFERENCES USERS(user_id) ON DELETE SET NULL
    )
  ]';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE CONTENT_REPORTS (
      report_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
      reporter_user_id NUMBER,
      target_type VARCHAR2(30) NOT NULL CHECK (target_type IN ('user', 'paper', 'review', 'question', 'answer')),
      target_id NUMBER NOT NULL,
      reason_code VARCHAR2(50) NOT NULL,
      details CLOB,
      status VARCHAR2(20) DEFAULT 'open' NOT NULL CHECK (status IN ('open', 'triaged', 'resolved', 'dismissed')),
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT fk_content_reports_reporter FOREIGN KEY (reporter_user_id) REFERENCES USERS(user_id) ON DELETE SET NULL
    )
  ]';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE MODERATION_CASES (
      case_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
      report_id NUMBER,
      target_type VARCHAR2(30) NOT NULL,
      target_id NUMBER NOT NULL,
      status VARCHAR2(20) DEFAULT 'open' NOT NULL CHECK (status IN ('open', 'investigating', 'resolved', 'dismissed')),
      priority VARCHAR2(20) DEFAULT 'normal' NOT NULL CHECK (priority IN ('low', 'normal', 'high', 'urgent')),
      assigned_admin_user_id NUMBER,
      resolution VARCHAR2(1000),
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT fk_moderation_cases_report FOREIGN KEY (report_id) REFERENCES CONTENT_REPORTS(report_id) ON DELETE SET NULL,
      CONSTRAINT fk_moderation_cases_assignee FOREIGN KEY (assigned_admin_user_id) REFERENCES USERS(user_id) ON DELETE SET NULL
    )
  ]';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE MODERATION_ACTIONS (
      action_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
      case_id NUMBER NOT NULL,
      actor_admin_user_id NUMBER NOT NULL,
      action_type VARCHAR2(30) NOT NULL CHECK (action_type IN ('hide', 'restore', 'warn', 'suspend', 'ban', 'edit_metadata', 'delete')),
      before_state CLOB CHECK (before_state IS JSON),
      after_state CLOB CHECK (after_state IS JSON),
      notes VARCHAR2(1000),
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT fk_moderation_actions_case FOREIGN KEY (case_id) REFERENCES MODERATION_CASES(case_id) ON DELETE CASCADE,
      CONSTRAINT fk_moderation_actions_actor FOREIGN KEY (actor_admin_user_id) REFERENCES USERS(user_id)
    )
  ]';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  FOR item IN (
    SELECT table_name FROM user_tables
    WHERE table_name IN ('RESEARCH_PAPERS', 'REVIEWS', 'QUESTIONS', 'ANSWERS')
  ) LOOP
    FOR column_to_add IN (
      SELECT 'STATUS' column_name, 'VARCHAR2(20) DEFAULT ''published'' NOT NULL CHECK (status IN (''draft'', ''published'', ''hidden'', ''removed'', ''pending_review''))' definition FROM dual
      UNION ALL SELECT 'VISIBILITY', 'VARCHAR2(20) DEFAULT ''public'' NOT NULL CHECK (visibility IN (''public'', ''network'', ''private''))' FROM dual
      UNION ALL SELECT 'DELETED_AT', 'TIMESTAMP' FROM dual
      UNION ALL SELECT 'DELETED_BY_USER_ID', 'NUMBER' FROM dual
    ) LOOP
      DECLARE
        column_count NUMBER;
      BEGIN
        SELECT COUNT(*) INTO column_count FROM user_tab_columns
        WHERE table_name = item.table_name AND column_name = column_to_add.column_name;
        IF column_count = 0 THEN
          EXECUTE IMMEDIATE 'ALTER TABLE ' || item.table_name || ' ADD (' || column_to_add.column_name || ' ' || column_to_add.definition || ')';
        END IF;
      END;
    END LOOP;
  END LOOP;
END;
/

BEGIN
  FOR item IN (
    SELECT 'RESEARCH_PAPERS' table_name, 'idx_papers_pub_state' index_name FROM dual
    UNION ALL SELECT 'REVIEWS', 'idx_reviews_pub_state' FROM dual
    UNION ALL SELECT 'QUESTIONS', 'idx_questions_pub_state' FROM dual
    UNION ALL SELECT 'ANSWERS', 'idx_answers_pub_state' FROM dual
  ) LOOP
    BEGIN
      EXECUTE IMMEDIATE 'CREATE INDEX ' || item.index_name || ' ON ' || item.table_name || ' (status, visibility, created_at)';
    EXCEPTION WHEN OTHERS THEN
      IF SQLCODE != -955 THEN RAISE; END IF;
    END;
  END LOOP;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_researcher_profiles_slug ON RESEARCHER_PROFILES (slug)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_user_follows_followed_at ON USER_FOLLOWS (followed_user_id, created_at)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_author_claims_queue ON USER_AUTHOR_CLAIMS (status, created_at)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_content_reports_status_at ON CONTENT_REPORTS (status, created_at)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_moderation_cases_queue ON MODERATION_CASES (status, priority, created_at)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

MERGE INTO ROLE_DEFINITIONS target
USING (
  SELECT 'researcher' role_key, 'Researcher' display_name, 'Creates and manages research content' description, 1 is_system FROM dual
  UNION ALL SELECT 'student', 'Student', 'Participates in research discovery and discussion', 1 FROM dual
  UNION ALL SELECT 'librarian', 'Librarian', 'Manages scholarly metadata and author claims', 1 FROM dual
  UNION ALL SELECT 'moderator', 'Moderator', 'Triages reports and moderates content', 1 FROM dual
  UNION ALL SELECT 'admin', 'Administrator', 'Manages platform operations and users', 1 FROM dual
) source ON (target.role_key = source.role_key)
WHEN NOT MATCHED THEN INSERT (role_key, display_name, description, is_system)
VALUES (source.role_key, source.display_name, source.description, source.is_system);

MERGE INTO PERMISSION_DEFINITIONS target
USING (
  SELECT 'profile.manage' permission_key, 'Manage own profile' description FROM dual
  UNION ALL SELECT 'content.moderate', 'Review and change moderated content state' FROM dual
  UNION ALL SELECT 'users.manage', 'Suspend, activate, and inspect users' FROM dual
  UNION ALL SELECT 'roles.manage', 'Assign platform roles' FROM dual
  UNION ALL SELECT 'email_queue.manage', 'Inspect and retry email queue items' FROM dual
  UNION ALL SELECT 'analytics.view', 'View platform analytics' FROM dual
  UNION ALL SELECT 'audit.view', 'View audit records' FROM dual
) source ON (target.permission_key = source.permission_key)
WHEN NOT MATCHED THEN INSERT (permission_key, description)
VALUES (source.permission_key, source.description);
