-- Idempotent migration for Institutions, Departments, and Flagged Publications.
-- Every block is wrapped in a PL/SQL block to handle already-existing tables or indexes.

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE INSTITUTIONS (
        institution_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        name VARCHAR2(255) UNIQUE NOT NULL,
        country VARCHAR2(100),
        created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )
  ]';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE DEPARTMENTS (
        department_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        name VARCHAR2(255) NOT NULL,
        institution_id NUMBER NOT NULL,
        created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT fk_departments_institution FOREIGN KEY (institution_id) REFERENCES INSTITUTIONS(institution_id) ON DELETE CASCADE,
        CONSTRAINT uq_dept UNIQUE (name, institution_id)
    )
  ]';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE FLAGGED_PUBLICATIONS (
        flag_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        paper_id NUMBER NOT NULL,
        reporter_user_id NUMBER NOT NULL,
        reason VARCHAR2(500) NOT NULL,
        status VARCHAR2(20) DEFAULT 'pending' NOT NULL CHECK (status IN ('pending', 'resolved', 'ignored')),
        created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT fk_flagged_paper FOREIGN KEY (paper_id) REFERENCES RESEARCH_PAPERS(paper_id) ON DELETE CASCADE,
        CONSTRAINT fk_flagged_reporter FOREIGN KEY (reporter_user_id) REFERENCES USERS(user_id) ON DELETE CASCADE
    )
  ]';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_flagged_paper ON FLAGGED_PUBLICATIONS(paper_id)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_flagged_reporter ON FLAGGED_PUBLICATIONS(reporter_user_id)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/
