-- Idempotent migration for JOBS and JOB_BOOKMARKS tables, and updating INSTITUTIONS.

BEGIN
  EXECUTE IMMEDIATE q'[
    ALTER TABLE INSTITUTIONS ADD logo_url VARCHAR2(500)
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1430 THEN -- ORA-01430: column being added already exists in table
      RAISE;
    END IF;
END;
/

BEGIN
  FOR item IN (
    SELECT 'INSTITUTION_ID' column_name, 'NUMBER' definition FROM dual
    UNION ALL SELECT 'COUNTRY', 'VARCHAR2(100)' FROM dual
    UNION ALL SELECT 'CITY', 'VARCHAR2(100)' FROM dual
    UNION ALL SELECT 'IS_NEW', 'NUMBER(1) DEFAULT 0 NOT NULL' FROM dual
    UNION ALL SELECT 'IS_EARLY_APPLICANT', 'NUMBER(1) DEFAULT 0 NOT NULL' FROM dual
    UNION ALL SELECT 'STATUS', 'VARCHAR2(50) DEFAULT ''PENDING_REVIEW'' NOT NULL' FROM dual
    UNION ALL SELECT 'DISCIPLINE', 'VARCHAR2(100)' FROM dual
    UNION ALL SELECT 'URL', 'VARCHAR2(500)' FROM dual
    UNION ALL SELECT 'CREATED_AT', 'TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL' FROM dual
  ) LOOP
    DECLARE
      existing_count NUMBER;
    BEGIN
      SELECT COUNT(*) INTO existing_count FROM user_tab_columns
      WHERE table_name = 'JOBS' AND column_name = item.column_name;
      IF existing_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE JOBS ADD (' || item.column_name || ' ' || item.definition || ')';
      END IF;
    END;
  END LOOP;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE JOBS (
        job_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title VARCHAR2(255) NOT NULL,
        institution_id NUMBER REFERENCES INSTITUTIONS(institution_id) ON DELETE CASCADE,
        country VARCHAR2(100),
        city VARCHAR2(100),
        description CLOB,
        is_new NUMBER(1) DEFAULT 0,
        is_early_applicant NUMBER(1) DEFAULT 0,
        status VARCHAR2(50) DEFAULT 'ACTIVE',
        discipline VARCHAR2(100),
        url VARCHAR2(500),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN -- ORA-00955: name is already used by an existing object
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE JOB_BOOKMARKS (
        bookmark_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id NUMBER REFERENCES USERS(user_id) ON DELETE CASCADE,
        job_id NUMBER REFERENCES JOBS(job_id) ON DELETE CASCADE,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT unique_job_bookmark UNIQUE (user_id, job_id)
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/
