BEGIN
  FOR item IN (
    SELECT 'RECIPIENT_USER_ID' column_name, 'NUMBER' definition FROM dual
    UNION ALL SELECT 'PAPER_ID', 'NUMBER' FROM dual
    UNION ALL SELECT 'REQUEST_TYPE', 'VARCHAR2(30) DEFAULT ''other'' NOT NULL' FROM dual
    UNION ALL SELECT 'DECISION_BY_USER_ID', 'NUMBER' FROM dual
    UNION ALL SELECT 'DECISION_REASON', 'VARCHAR2(1000)' FROM dual
    UNION ALL SELECT 'EXPIRES_AT', 'TIMESTAMP' FROM dual
  ) LOOP
    DECLARE
      existing_count NUMBER;
    BEGIN
      SELECT COUNT(*) INTO existing_count FROM user_tab_columns
      WHERE table_name = 'RESEARCH_REQUESTS' AND column_name = item.column_name;
      IF existing_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE RESEARCH_REQUESTS ADD (' || item.column_name || ' ' || item.definition || ')';
      END IF;
    END;
  END LOOP;
END;
/

BEGIN
  FOR item IN (
    SELECT constraint_name FROM user_constraints
    WHERE table_name = 'RESEARCH_REQUESTS'
      AND constraint_type = 'C'
      AND search_condition_vc LIKE '%status IN%'
  ) LOOP
    EXECUTE IMMEDIATE 'ALTER TABLE RESEARCH_REQUESTS DROP CONSTRAINT ' || item.constraint_name;
  END LOOP;
  EXECUTE IMMEDIATE 'ALTER TABLE RESEARCH_REQUESTS ADD CONSTRAINT ck_research_requests_status_v2 CHECK (status IN (''pending'', ''approved'', ''declined'', ''cancelled'', ''expired'', ''archived''))';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-2261, -2264, -2275) THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE RESEARCH_REQUESTS ADD CONSTRAINT fk_research_requests_recipient FOREIGN KEY (recipient_user_id) REFERENCES USERS(user_id) ON DELETE CASCADE';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-2261, -2264, -2275) THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE RESEARCH_REQUESTS ADD CONSTRAINT fk_research_requests_paper FOREIGN KEY (paper_id) REFERENCES RESEARCH_PAPERS(paper_id) ON DELETE SET NULL';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-2261, -2264, -2275) THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE RESEARCH_REQUESTS ADD CONSTRAINT fk_research_requests_decider FOREIGN KEY (decision_by_user_id) REFERENCES USERS(user_id) ON DELETE SET NULL';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-2261, -2264, -2275) THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_research_requests_recipient ON RESEARCH_REQUESTS(recipient_user_id, status, created_at)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE MESSAGES (
      message_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
      sender_id NUMBER NOT NULL,
      receiver_id NUMBER NOT NULL,
      content CLOB NOT NULL,
      is_read NUMBER(1) DEFAULT 0 NOT NULL CHECK (is_read IN (0, 1)),
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT ck_messages_distinct_users CHECK (sender_id <> receiver_id),
      CONSTRAINT fk_messages_sender FOREIGN KEY (sender_id) REFERENCES USERS(user_id) ON DELETE CASCADE,
      CONSTRAINT fk_messages_receiver FOREIGN KEY (receiver_id) REFERENCES USERS(user_id) ON DELETE CASCADE
    )
  ]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE MESSAGE_REQUESTS (
      request_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
      sender_id NUMBER NOT NULL,
      recipient_id NUMBER NOT NULL,
      first_message CLOB NOT NULL,
      status VARCHAR2(20) DEFAULT 'pending' NOT NULL CHECK (status IN ('pending', 'accepted', 'declined', 'blocked')),
      decided_by_user_id NUMBER,
      decided_at TIMESTAMP,
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT ck_message_requests_distinct CHECK (sender_id <> recipient_id),
      CONSTRAINT uq_message_request_pair UNIQUE (sender_id, recipient_id),
      CONSTRAINT fk_message_requests_sender FOREIGN KEY (sender_id) REFERENCES USERS(user_id) ON DELETE CASCADE,
      CONSTRAINT fk_message_requests_recipient FOREIGN KEY (recipient_id) REFERENCES USERS(user_id) ON DELETE CASCADE,
      CONSTRAINT fk_message_requests_decider FOREIGN KEY (decided_by_user_id) REFERENCES USERS(user_id) ON DELETE SET NULL
    )
  ]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE USER_BLOCKS (
      blocker_user_id NUMBER NOT NULL,
      blocked_user_id NUMBER NOT NULL,
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT pk_user_blocks PRIMARY KEY (blocker_user_id, blocked_user_id),
      CONSTRAINT ck_user_blocks_distinct CHECK (blocker_user_id <> blocked_user_id),
      CONSTRAINT fk_user_blocks_blocker FOREIGN KEY (blocker_user_id) REFERENCES USERS(user_id) ON DELETE CASCADE,
      CONSTRAINT fk_user_blocks_blocked FOREIGN KEY (blocked_user_id) REFERENCES USERS(user_id) ON DELETE CASCADE
    )
  ]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE RESEARCHER_VERIFICATION_REQUESTS (
      verification_request_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
      user_id NUMBER NOT NULL,
      institutional_email VARCHAR2(320) NOT NULL,
      institutional_domain VARCHAR2(255) NOT NULL,
      status VARCHAR2(20) DEFAULT 'pending' NOT NULL CHECK (status IN ('pending', 'approved', 'rejected')),
      evidence CLOB,
      rejection_reason VARCHAR2(1000),
      reviewed_by_user_id NUMBER,
      reviewed_at TIMESTAMP,
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT uq_verification_request_user UNIQUE (user_id),
      CONSTRAINT fk_verification_request_user FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE,
      CONSTRAINT fk_verification_request_reviewer FOREIGN KEY (reviewed_by_user_id) REFERENCES USERS(user_id) ON DELETE SET NULL
    )
  ]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE ACTIVITY_EVENTS (
      event_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
      recipient_user_id NUMBER NOT NULL,
      actor_user_id NUMBER,
      event_type VARCHAR2(40) NOT NULL,
      source_type VARCHAR2(30),
      source_id NUMBER,
      title VARCHAR2(200) NOT NULL,
      body VARCHAR2(1000),
      route_url VARCHAR2(500),
      is_read NUMBER(1) DEFAULT 0 NOT NULL CHECK (is_read IN (0, 1)),
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      read_at TIMESTAMP,
      CONSTRAINT fk_activity_recipient FOREIGN KEY (recipient_user_id) REFERENCES USERS(user_id) ON DELETE CASCADE,
      CONSTRAINT fk_activity_actor FOREIGN KEY (actor_user_id) REFERENCES USERS(user_id) ON DELETE SET NULL
    )
  ]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE USER_FILES (
      file_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
      user_id NUMBER NOT NULL,
      storage_key VARCHAR2(500) NOT NULL,
      original_name VARCHAR2(255) NOT NULL,
      mime_type VARCHAR2(120) NOT NULL,
      size_bytes NUMBER NOT NULL,
      status VARCHAR2(20) DEFAULT 'available' NOT NULL CHECK (status IN ('available', 'deleted')),
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT fk_user_files_user FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE
    )
  ]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  FOR item IN (
    SELECT 'FILE_KIND' column_name, 'VARCHAR2(20) DEFAULT ''paper'' NOT NULL' definition FROM dual
  ) LOOP
    DECLARE
      existing_count NUMBER;
    BEGIN
      SELECT COUNT(*) INTO existing_count FROM user_tab_columns
      WHERE table_name = 'PAPER_FILES' AND column_name = item.column_name;
      IF existing_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE PAPER_FILES ADD (' || item.column_name || ' ' || item.definition || ')';
      END IF;
    END;
  END LOOP;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_messages_receiver_read ON MESSAGES(receiver_id, is_read, created_at)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_messages_pair ON MESSAGES(sender_id, receiver_id, created_at)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_message_requests_recipient ON MESSAGE_REQUESTS(recipient_id, status, created_at)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_verification_queue ON RESEARCHER_VERIFICATION_REQUESTS(status, created_at)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_activity_recipient_read ON ACTIVITY_EVENTS(recipient_user_id, is_read, created_at)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  FOR item IN (
    SELECT 'REMOTE_MODE' column_name, 'VARCHAR2(20) DEFAULT ''on_site'' NOT NULL' definition FROM dual
    UNION ALL SELECT 'CAREER_LEVEL', 'VARCHAR2(40)' FROM dual
  ) LOOP
    DECLARE
      existing_count NUMBER;
    BEGIN
      SELECT COUNT(*) INTO existing_count FROM user_tab_columns
      WHERE table_name = 'JOBS' AND column_name = item.column_name;
      IF existing_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE JOBS ADD (' || item.column_name || ' ' || item.definition || ')';
      END IF;
    END;
  END LOOP;
END;
/

CREATE OR REPLACE PACKAGE PKG_PROFILE AS
  PROCEDURE get_public_profile(
    p_slug IN VARCHAR2,
    p_profile OUT SYS_REFCURSOR,
    p_papers OUT SYS_REFCURSOR,
    p_questions OUT SYS_REFCURSOR
  );
  PROCEDURE get_all_researchers(p_limit IN NUMBER, p_offset IN NUMBER, p_out OUT SYS_REFCURSOR);
  PROCEDURE get_contributions(p_user_id IN NUMBER, p_limit IN NUMBER, p_offset IN NUMBER, p_out OUT SYS_REFCURSOR);
  PROCEDURE ensure_profile(p_user_id IN NUMBER, p_slug IN VARCHAR2);
  PROCEDURE update_profile(
    p_user_id IN NUMBER,
    p_headline IN VARCHAR2,
    p_department IN VARCHAR2,
    p_position_title IN VARCHAR2,
    p_website_url IN VARCHAR2,
    p_orcid IN VARCHAR2,
    p_visibility IN VARCHAR2
  );
  PROCEDURE follow_user(p_follower_user_id IN NUMBER, p_followed_user_id IN NUMBER);
  PROCEDURE unfollow_user(p_follower_user_id IN NUMBER, p_followed_user_id IN NUMBER);
END PKG_PROFILE;
/

CREATE OR REPLACE PACKAGE BODY PKG_PROFILE AS
  PROCEDURE get_public_profile(
    p_slug IN VARCHAR2,
    p_profile OUT SYS_REFCURSOR,
    p_papers OUT SYS_REFCURSOR,
    p_questions OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN p_profile FOR
      SELECT u.user_id, u.username, u.full_name, u.affiliation, u.country, u.profile_picture_url, u.bio,
             u.email_verified_at, u.researcher_verified_at, u.is_verified,
             rp.slug, rp.headline, rp.department, rp.position_title, rp.website_url, rp.orcid,
             NVL(rs.followers, 0) followers, NVL(rs.following, 0) following, NVL(rs.total_reads, 0) total_reads,
             NVL(rs.rg_score, 0) rg_score,
             (SELECT NVL(SUM(p.citation_count), 0) FROM PAPER_AUTHORS pa JOIN USER_AUTHOR_CLAIMS c ON c.author_id = pa.author_id AND c.user_id = u.user_id AND c.status = 'verified' JOIN RESEARCH_PAPERS p ON p.paper_id = pa.paper_id WHERE p.status = 'published') citations,
             (SELECT COUNT(*) FROM PAPER_AUTHORS pa JOIN USER_AUTHOR_CLAIMS c ON c.author_id = pa.author_id AND c.user_id = u.user_id AND c.status = 'verified' JOIN RESEARCH_PAPERS p ON p.paper_id = pa.paper_id WHERE p.status = 'published') publication_count,
             (SELECT JSON_ARRAYAGG(JSON_OBJECT('education_id' VALUE e.education_id, 'institution' VALUE e.institution, 'degree' VALUE e.degree, 'field_of_study' VALUE e.field_of_study, 'start_year' VALUE e.start_year, 'end_year' VALUE e.end_year)) FROM USER_EDUCATION e WHERE e.user_id = u.user_id) education_json,
             (SELECT JSON_ARRAYAGG(JSON_OBJECT('experience_id' VALUE ex.experience_id, 'company' VALUE ex.company, 'position' VALUE ex.position, 'start_date' VALUE TO_CHAR(ex.start_date, 'YYYY-MM-DD'), 'end_date' VALUE TO_CHAR(ex.end_date, 'YYYY-MM-DD'), 'description' VALUE TO_CHAR(ex.description))) FROM USER_EXPERIENCE ex WHERE ex.user_id = u.user_id) experience_json,
             (SELECT JSON_ARRAYAGG(JSON_OBJECT('skill_id' VALUE s.skill_id, 'skill_name' VALUE s.skill_name)) FROM USER_SKILLS s WHERE s.user_id = u.user_id) skills_json,
             (SELECT JSON_ARRAYAGG(JSON_OBJECT('language_id' VALUE l.language_id, 'language_name' VALUE l.language_name, 'proficiency' VALUE l.proficiency)) FROM USER_LANGUAGES l WHERE l.user_id = u.user_id) languages_json,
             (SELECT JSON_ARRAYAGG(JSON_OBJECT('discipline_id' VALUE d.discipline_id, 'discipline_name' VALUE d.discipline_name)) FROM USER_DISCIPLINES d WHERE d.user_id = u.user_id) disciplines_json
      FROM RESEARCHER_PROFILES rp
      JOIN USERS u ON u.user_id = rp.user_id
      LEFT JOIN RESEARCHER_STATS rs ON rs.user_id = u.user_id
      WHERE rp.slug = LOWER(TRIM(p_slug)) AND rp.visibility = 'public' AND u.is_active = 1;

    OPEN p_papers FOR
      SELECT p.paper_id, p.title, p.abstract, p.publication_date, p.citation_count, p.view_count, p.download_count, p.cover_image_url, j.name journal_name
      FROM RESEARCHER_PROFILES rp
      JOIN USER_AUTHOR_CLAIMS claim ON claim.user_id = rp.user_id AND claim.status = 'verified'
      JOIN PAPER_AUTHORS pa ON pa.author_id = claim.author_id
      JOIN RESEARCH_PAPERS p ON p.paper_id = pa.paper_id
      LEFT JOIN JOURNALS j ON j.journal_id = p.journal_id
      WHERE rp.slug = LOWER(TRIM(p_slug)) AND p.status = 'published' AND p.visibility = 'public'
      ORDER BY p.publication_date DESC, p.paper_id DESC;

    OPEN p_questions FOR
      SELECT q.question_id, q.title, q.body, q.category, q.view_count, q.answer_count, q.created_at
      FROM RESEARCHER_PROFILES rp JOIN QUESTIONS q ON q.user_id = rp.user_id
      WHERE rp.slug = LOWER(TRIM(p_slug)) AND q.status = 'published' AND q.visibility = 'public'
      ORDER BY q.created_at DESC;
  END get_public_profile;

  PROCEDURE get_all_researchers(p_limit IN NUMBER, p_offset IN NUMBER, p_out OUT SYS_REFCURSOR) AS
  BEGIN
    OPEN p_out FOR SELECT * FROM (
      SELECT u.user_id, u.username, u.full_name, u.affiliation, u.country, u.profile_picture_url, u.bio, rp.slug, rp.headline, rp.department, rp.position_title, rp.website_url, rp.orcid, NVL(rs.followers, 0) followers, NVL(rs.following, 0) following, NVL(rs.total_reads, 0) total_reads, NVL(rs.rg_score, 0) rg_score,
             ROW_NUMBER() OVER (ORDER BY NVL(rs.followers, 0) DESC, u.user_id DESC) rn
      FROM RESEARCHER_PROFILES rp JOIN USERS u ON u.user_id = rp.user_id LEFT JOIN RESEARCHER_STATS rs ON rs.user_id = u.user_id
      WHERE rp.visibility = 'public' AND u.is_active = 1
    ) WHERE rn > NVL(p_offset, 0) AND rn <= NVL(p_offset, 0) + NVL(p_limit, 20);
  END get_all_researchers;

  PROCEDURE get_contributions(p_user_id IN NUMBER, p_limit IN NUMBER, p_offset IN NUMBER, p_out OUT SYS_REFCURSOR) AS
  BEGIN
    OPEN p_out FOR SELECT contribution_type, contribution_id, title, summary, created_at, metric_value, route_url FROM (
      SELECT contribution_type, contribution_id, title, summary, created_at, metric_value, route_url,
             ROW_NUMBER() OVER (ORDER BY created_at DESC, contribution_id DESC) rn FROM (
        SELECT 'publication' contribution_type, p.paper_id contribution_id, p.title, DBMS_LOB.SUBSTR(p.abstract, 1000, 1) summary, p.created_at, p.citation_count metric_value, '/papers/' || p.paper_id route_url
        FROM RESEARCH_PAPERS p JOIN PAPER_AUTHORS pa ON pa.paper_id = p.paper_id JOIN USER_AUTHOR_CLAIMS c ON c.author_id = pa.author_id AND c.user_id = p_user_id AND c.status = 'verified'
        WHERE p.status = 'published' AND p.visibility = 'public'
        UNION ALL
        SELECT 'question', q.question_id, q.title, DBMS_LOB.SUBSTR(q.body, 1000, 1), q.created_at, q.answer_count, '/questions/' || q.question_id
        FROM QUESTIONS q WHERE q.user_id = p_user_id AND q.status = 'published' AND q.visibility = 'public'
        UNION ALL
        SELECT 'review', r.review_id, 'Review of ' || p.title, DBMS_LOB.SUBSTR(r.review_text, 1000, 1), r.created_at, r.is_helpful, '/papers/' || p.paper_id
        FROM REVIEWS r JOIN RESEARCH_PAPERS p ON p.paper_id = r.paper_id WHERE r.user_id = p_user_id AND r.status = 'published' AND r.visibility = 'public'
        UNION ALL
        SELECT 'job', j.job_id, j.title, DBMS_LOB.SUBSTR(j.description, 1000, 1), j.created_at, 0, '/jobs/' || j.job_id
        FROM JOBS j WHERE j.posted_by = p_user_id AND j.status IN ('ACTIVE', 'PUBLISHED')
      )
    ) WHERE rn > NVL(p_offset, 0) AND rn <= NVL(p_offset, 0) + NVL(p_limit, 20) ORDER BY rn;
  END get_contributions;

  PROCEDURE ensure_profile(p_user_id IN NUMBER, p_slug IN VARCHAR2) AS
  BEGIN
    MERGE INTO RESEARCHER_PROFILES target USING (SELECT p_user_id user_id, LOWER(TRIM(p_slug)) slug FROM dual) source ON (target.user_id = source.user_id)
    WHEN MATCHED THEN UPDATE SET target.slug = source.slug, target.updated_at = SYSTIMESTAMP
    WHEN NOT MATCHED THEN INSERT (user_id, slug) VALUES (source.user_id, source.slug);
  END ensure_profile;

  PROCEDURE update_profile(p_user_id IN NUMBER, p_headline IN VARCHAR2, p_department IN VARCHAR2, p_position_title IN VARCHAR2, p_website_url IN VARCHAR2, p_orcid IN VARCHAR2, p_visibility IN VARCHAR2) AS
  BEGIN
    IF p_visibility NOT IN ('public', 'network', 'private') THEN RAISE_APPLICATION_ERROR(-20002, 'Invalid profile visibility'); END IF;
    UPDATE RESEARCHER_PROFILES SET headline = p_headline, department = p_department, position_title = p_position_title, website_url = p_website_url, orcid = p_orcid, visibility = p_visibility, profile_completed_at = SYSTIMESTAMP, updated_at = SYSTIMESTAMP WHERE user_id = p_user_id;
    IF SQL%ROWCOUNT = 0 THEN RAISE_APPLICATION_ERROR(-20003, 'Researcher profile not found'); END IF;
  END update_profile;

  PROCEDURE follow_user(p_follower_user_id IN NUMBER, p_followed_user_id IN NUMBER) AS
  BEGIN
    IF p_follower_user_id = p_followed_user_id THEN RAISE_APPLICATION_ERROR(-20004, 'A user cannot follow themselves'); END IF;
    INSERT INTO USER_FOLLOWS (follower_user_id, followed_user_id) VALUES (p_follower_user_id, p_followed_user_id);
    INSERT INTO ACTIVITY_EVENTS (recipient_user_id, actor_user_id, event_type, source_type, source_id, title, body, route_url) SELECT p_followed_user_id, p_follower_user_id, 'new_follower', 'researcher', p_follower_user_id, 'New researcher follower', u.full_name || ' started following you', '/researchers/' || u.username FROM USERS u WHERE u.user_id = p_follower_user_id;
  EXCEPTION WHEN DUP_VAL_ON_INDEX THEN RAISE_APPLICATION_ERROR(-20005, 'Already following this researcher');
  END follow_user;

  PROCEDURE unfollow_user(p_follower_user_id IN NUMBER, p_followed_user_id IN NUMBER) AS
  BEGIN
    DELETE FROM USER_FOLLOWS WHERE follower_user_id = p_follower_user_id AND followed_user_id = p_followed_user_id;
    IF SQL%ROWCOUNT = 0 THEN RAISE_APPLICATION_ERROR(-20006, 'Not following this researcher'); END IF;
  END unfollow_user;
END PKG_PROFILE;
/

CREATE OR REPLACE PACKAGE PKG_NETWORK AS
  PROCEDURE get_recommendations(p_user_id IN NUMBER, p_limit IN NUMBER, p_out OUT SYS_REFCURSOR);
END PKG_NETWORK;
/

CREATE OR REPLACE PACKAGE BODY PKG_NETWORK AS
  PROCEDURE get_recommendations(p_user_id IN NUMBER, p_limit IN NUMBER, p_out OUT SYS_REFCURSOR) AS
  BEGIN
    OPEN p_out FOR SELECT * FROM (
      SELECT u.user_id, u.username, u.full_name, u.affiliation, u.country, u.profile_picture_url, rp.slug, rp.headline, rp.department, rp.position_title,
        (3 * (SELECT COUNT(*) FROM USER_DISCIPLINES a JOIN USER_DISCIPLINES b ON LOWER(a.discipline_name) = LOWER(b.discipline_name) WHERE a.user_id = p_user_id AND b.user_id = u.user_id)) +
        CASE WHEN LOWER(NVL(u.affiliation, '#')) = LOWER(NVL((SELECT affiliation FROM USERS WHERE user_id = p_user_id), '!')) THEN 4 ELSE 0 END +
        (2 * (SELECT COUNT(*) FROM PAPER_AUTHORS pa JOIN USER_AUTHOR_CLAIMS c1 ON c1.author_id = pa.author_id AND c1.user_id = p_user_id AND c1.status = 'verified' JOIN USER_AUTHOR_CLAIMS c2 ON c2.author_id = pa.author_id AND c2.user_id = u.user_id AND c2.status = 'verified')) +
        (SELECT COUNT(*) FROM USER_FOLLOWS f1 JOIN USER_FOLLOWS f2 ON f1.followed_user_id = f2.followed_user_id WHERE f1.follower_user_id = p_user_id AND f2.follower_user_id = u.user_id) score,
        CASE WHEN LOWER(NVL(u.affiliation, '#')) = LOWER(NVL((SELECT affiliation FROM USERS WHERE user_id = p_user_id), '!')) THEN 'same_institution'
          WHEN EXISTS (SELECT 1 FROM USER_DISCIPLINES a JOIN USER_DISCIPLINES b ON LOWER(a.discipline_name) = LOWER(b.discipline_name) WHERE a.user_id = p_user_id AND b.user_id = u.user_id) THEN 'shared_field'
          WHEN EXISTS (SELECT 1 FROM PAPER_AUTHORS pa JOIN USER_AUTHOR_CLAIMS c1 ON c1.author_id = pa.author_id AND c1.user_id = p_user_id AND c1.status = 'verified' JOIN USER_AUTHOR_CLAIMS c2 ON c2.author_id = pa.author_id AND c2.user_id = u.user_id AND c2.status = 'verified') THEN 'coauthor'
          ELSE 'similar_research' END recommendation_reason
      FROM USERS u JOIN RESEARCHER_PROFILES rp ON rp.user_id = u.user_id
      WHERE u.user_id <> p_user_id AND u.is_active = 1 AND u.account_status = 'active' AND rp.visibility = 'public'
        AND NOT EXISTS (SELECT 1 FROM USER_FOLLOWS f WHERE f.follower_user_id = p_user_id AND f.followed_user_id = u.user_id)
        AND NOT EXISTS (SELECT 1 FROM USER_BLOCKS b WHERE (b.blocker_user_id = p_user_id AND b.blocked_user_id = u.user_id) OR (b.blocker_user_id = u.user_id AND b.blocked_user_id = p_user_id))
      ORDER BY score DESC, u.user_id DESC
    ) WHERE ROWNUM <= NVL(p_limit, 20);
  END get_recommendations;
END PKG_NETWORK;
/
