BEGIN
  FOR item IN (
    SELECT 'PUBLICATION_TYPE' column_name, 'VARCHAR2(40) DEFAULT ''article'' NOT NULL' definition FROM dual
    UNION ALL SELECT 'IS_OPEN_ACCESS', 'NUMBER(1) DEFAULT 0 NOT NULL CHECK (is_open_access IN (0, 1))' FROM dual
  ) LOOP
    DECLARE
      existing_count NUMBER;
    BEGIN
      SELECT COUNT(*) INTO existing_count
      FROM user_tab_columns
      WHERE table_name = 'RESEARCH_PAPERS' AND column_name = item.column_name;
      IF existing_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE RESEARCH_PAPERS ADD (' || item.column_name || ' ' || item.definition || ')';
      END IF;
    END;
  END LOOP;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE USER_INTERESTS (
      user_id NUMBER NOT NULL,
      interest_type VARCHAR2(30) NOT NULL CHECK (interest_type IN ('field', 'keyword', 'journal', 'researcher', 'author')),
      interest_id NUMBER NOT NULL,
      source VARCHAR2(20) DEFAULT 'explicit' NOT NULL CHECK (source IN ('explicit', 'inferred')),
      weight NUMBER(5,2) DEFAULT 1 NOT NULL,
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT pk_user_interests PRIMARY KEY (user_id, interest_type, interest_id),
      CONSTRAINT fk_user_interests_user FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE
    )
  ]';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE USER_FEED_ACTIONS (
      user_id NUMBER NOT NULL,
      paper_id NUMBER NOT NULL,
      action_type VARCHAR2(30) NOT NULL CHECK (action_type IN ('not_interested', 'mute')),
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT pk_user_feed_actions PRIMARY KEY (user_id, paper_id, action_type),
      CONSTRAINT fk_user_feed_actions_user FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE,
      CONSTRAINT fk_user_feed_actions_paper FOREIGN KEY (paper_id) REFERENCES RESEARCH_PAPERS(paper_id) ON DELETE CASCADE
    )
  ]';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE PAPER_FILES (
      file_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
      paper_id NUMBER NOT NULL,
      owner_user_id NUMBER NOT NULL,
      storage_key VARCHAR2(500) NOT NULL UNIQUE,
      original_name VARCHAR2(255) NOT NULL,
      mime_type VARCHAR2(120) NOT NULL,
      size_bytes NUMBER NOT NULL CHECK (size_bytes > 0),
      checksum_sha256 VARCHAR2(64) NOT NULL,
      visibility VARCHAR2(20) DEFAULT 'public' NOT NULL CHECK (visibility IN ('public', 'network', 'private')),
      status VARCHAR2(20) DEFAULT 'available' NOT NULL CHECK (status IN ('pending', 'available', 'quarantined', 'deleted')),
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT fk_paper_files_paper FOREIGN KEY (paper_id) REFERENCES RESEARCH_PAPERS(paper_id) ON DELETE CASCADE,
      CONSTRAINT fk_paper_files_owner FOREIGN KEY (owner_user_id) REFERENCES USERS(user_id) ON DELETE CASCADE
    )
  ]';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_user_interests_type ON USER_INTERESTS (user_id, interest_type, interest_id)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_user_feed_actions_paper ON USER_FEED_ACTIONS (user_id, paper_id, action_type)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_paper_files_paper ON PAPER_FILES (paper_id, status)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

CREATE OR REPLACE PACKAGE PKG_DISCOVERY AS
  PROCEDURE get_feed(
    p_user_id IN NUMBER,
    p_before_date IN DATE,
    p_before_id IN NUMBER,
    p_before_priority IN NUMBER,
    p_limit IN NUMBER,
    p_cursor OUT SYS_REFCURSOR
  );
END PKG_DISCOVERY;
/

CREATE OR REPLACE PACKAGE BODY PKG_DISCOVERY AS
  PROCEDURE get_feed(
    p_user_id IN NUMBER,
    p_before_date IN DATE,
    p_before_id IN NUMBER,
    p_before_priority IN NUMBER,
    p_limit IN NUMBER,
    p_cursor OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN p_cursor FOR
      WITH scored AS (
        SELECT
          p.paper_id,
          p.title,
          p.abstract,
          p.publication_date,
          p.doi,
          p.journal_id,
          j.name AS journal_name,
          p.citation_count,
          p.view_count,
          p.download_count,
          p.pdf_url,
          p.language,
          p.is_peer_reviewed,
          p.publication_type,
          p.is_open_access,
          CASE
            WHEN p_user_id IS NOT NULL AND EXISTS (
              SELECT 1
              FROM PAPER_AUTHORS pa
              JOIN USER_AUTHOR_CLAIMS uac ON uac.author_id = pa.author_id AND uac.status = 'verified'
              JOIN USER_FOLLOWS uf ON uf.followed_user_id = uac.user_id
              WHERE pa.paper_id = p.paper_id AND uf.follower_user_id = p_user_id
            ) THEN 3
            WHEN p_user_id IS NOT NULL AND EXISTS (
              SELECT 1 FROM PAPER_AUTHORS pa
              JOIN FOLLOWED_AUTHORS fa ON fa.author_id = pa.author_id
              WHERE pa.paper_id = p.paper_id AND fa.user_id = p_user_id
            ) THEN 2
            WHEN p_user_id IS NOT NULL AND EXISTS (
              SELECT 1
              FROM USER_INTERESTS ui
              WHERE ui.user_id = p_user_id
                AND (
                  (ui.interest_type = 'field' AND EXISTS (SELECT 1 FROM PAPER_FIELDS pf WHERE pf.paper_id = p.paper_id AND pf.field_id = ui.interest_id))
                  OR (ui.interest_type = 'keyword' AND EXISTS (SELECT 1 FROM PAPER_KEYWORDS pk WHERE pk.paper_id = p.paper_id AND pk.keyword_id = ui.interest_id))
                  OR (ui.interest_type = 'journal' AND ui.interest_id = p.journal_id)
                  OR (ui.interest_type = 'author' AND EXISTS (SELECT 1 FROM PAPER_AUTHORS pa WHERE pa.paper_id = p.paper_id AND pa.author_id = ui.interest_id))
                )
            ) THEN 1
            ELSE 0
          END AS feed_priority
        FROM RESEARCH_PAPERS p
        LEFT JOIN JOURNALS j ON j.journal_id = p.journal_id
        WHERE NVL(p.status, 'published') = 'published'
          AND NVL(p.visibility, 'public') = 'public'
          AND (p_user_id IS NULL OR NOT EXISTS (
            SELECT 1 FROM USER_FEED_ACTIONS ufa
            WHERE ufa.user_id = p_user_id AND ufa.paper_id = p.paper_id
          ))
      ),
      filtered AS (
        SELECT scored.*,
          CASE feed_priority
            WHEN 3 THEN 'followed_researcher'
            WHEN 2 THEN 'followed_author'
            WHEN 1 THEN 'interest_match'
            ELSE 'discovery'
          END AS feed_reason
        FROM scored
        WHERE p_before_date IS NULL
           OR feed_priority < NVL(p_before_priority, 0)
           OR (feed_priority = NVL(p_before_priority, 0) AND (
                publication_date < p_before_date
                OR (publication_date = p_before_date AND paper_id < NVL(p_before_id, 999999999999))
           ))
      ),
      selected AS (
        SELECT filtered.*, ROW_NUMBER() OVER (
          ORDER BY feed_priority DESC, publication_date DESC, paper_id DESC
        ) AS row_number_value
        FROM filtered
      )
      SELECT
        s.paper_id,
        s.title,
        s.abstract,
        s.publication_date,
        s.doi,
        s.journal_id,
        s.journal_name,
        s.citation_count,
        s.view_count,
        s.download_count,
        s.pdf_url,
        s.language,
        s.is_peer_reviewed,
        s.publication_type,
        s.is_open_access,
        s.feed_priority,
        s.feed_reason,
        pa.author_id,
        pa.author_order,
        a.full_name AS author_name,
        a.affiliation AS author_affiliation,
        a.country AS author_country,
        a.orcid AS author_orcid,
        uac.user_id AS claimed_user_id,
        rp.slug AS claimed_profile_slug,
        rp.headline AS claimed_profile_headline
      FROM selected s
      LEFT JOIN PAPER_AUTHORS pa ON pa.paper_id = s.paper_id
      LEFT JOIN AUTHORS a ON a.author_id = pa.author_id
      LEFT JOIN USER_AUTHOR_CLAIMS uac ON uac.author_id = pa.author_id AND uac.status = 'verified'
      LEFT JOIN RESEARCHER_PROFILES rp ON rp.user_id = uac.user_id
      WHERE s.row_number_value <= LEAST(NVL(p_limit, 20), 100)
      ORDER BY s.feed_priority DESC, s.publication_date DESC, s.paper_id DESC, pa.author_order;
  END get_feed;
END PKG_DISCOVERY;
/
