BEGIN
  FOR item IN (
    SELECT 'EMAIL_VERIFIED_AT' column_name, 'TIMESTAMP' definition FROM dual
    UNION ALL SELECT 'RESEARCHER_VERIFIED_AT', 'TIMESTAMP' FROM dual
    UNION ALL SELECT 'ACCOUNT_STATUS', 'VARCHAR2(20) DEFAULT ''active'' NOT NULL' FROM dual
    UNION ALL SELECT 'SUSPENSION_UNTIL', 'TIMESTAMP' FROM dual
    UNION ALL SELECT 'BAN_REASON', 'VARCHAR2(1000)' FROM dual
    UNION ALL SELECT 'BANNED_AT', 'TIMESTAMP' FROM dual
  ) LOOP
    DECLARE
      existing_count NUMBER;
    BEGIN
      SELECT COUNT(*) INTO existing_count FROM user_tab_columns
      WHERE table_name = 'USERS' AND column_name = item.column_name;
      IF existing_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE USERS ADD (' || item.column_name || ' ' || item.definition || ')';
      END IF;
    END;
  END LOOP;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE USERS ADD CONSTRAINT ck_users_account_status CHECK (account_status IN (''active'', ''suspended'', ''banned'', ''closed''))';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-2261, -2264) THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE EMAIL_IDENTITIES (
      normalized_email VARCHAR2(320) PRIMARY KEY,
      original_email VARCHAR2(320) NOT NULL,
      user_id NUMBER,
      reserved_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT fk_email_identity_user FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE SET NULL
    )
  ]';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  INSERT INTO EMAIL_IDENTITIES (normalized_email, original_email, user_id)
  SELECT LOWER(TRIM(email)), email, user_id FROM USERS u
  WHERE NOT EXISTS (SELECT 1 FROM EMAIL_IDENTITIES e WHERE e.normalized_email = LOWER(TRIM(u.email)));
  COMMIT;
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-1, -955) THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE AUTH_TOKENS (
      token_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
      user_id NUMBER NOT NULL,
      token_hash VARCHAR2(128) NOT NULL UNIQUE,
      token_type VARCHAR2(30) NOT NULL CHECK (token_type IN ('email_verification', 'password_reset')),
      expires_at TIMESTAMP NOT NULL,
      used_at TIMESTAMP,
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT fk_auth_tokens_user FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE
    )
  ]';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE SUPPORT_TICKETS (
      ticket_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
      user_id NUMBER,
      ticket_type VARCHAR2(30) NOT NULL CHECK (ticket_type IN ('glitch', 'account', 'safety', 'content')),
      subject VARCHAR2(300) NOT NULL,
      details CLOB NOT NULL,
      status VARCHAR2(20) DEFAULT 'open' NOT NULL CHECK (status IN ('open', 'in_progress', 'resolved', 'closed')),
      assigned_to_user_id NUMBER,
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT fk_support_ticket_user FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE SET NULL,
      CONSTRAINT fk_support_ticket_assignee FOREIGN KEY (assigned_to_user_id) REFERENCES USERS(user_id) ON DELETE SET NULL
    )
  ]';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE MODERATION_APPEALS (
      appeal_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
      user_id NUMBER NOT NULL,
      action_id NUMBER,
      details CLOB NOT NULL,
      status VARCHAR2(20) DEFAULT 'open' NOT NULL CHECK (status IN ('open', 'reviewing', 'upheld', 'reversed')),
      reviewed_by_user_id NUMBER,
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT fk_appeal_user FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE,
      CONSTRAINT fk_appeal_action FOREIGN KEY (action_id) REFERENCES MODERATION_ACTIONS(action_id) ON DELETE SET NULL,
      CONSTRAINT fk_appeal_reviewer FOREIGN KEY (reviewed_by_user_id) REFERENCES USERS(user_id) ON DELETE SET NULL
    )
  ]';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_auth_tokens_lookup ON AUTH_TOKENS (user_id, token_type, expires_at)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_support_tickets_queue ON SUPPORT_TICKETS (status, created_at)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_moderation_appeals_queue ON MODERATION_APPEALS (status, created_at)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/
